import Header from "@/components/Header";

export const metadata = {
  title: {
    template: "%s | AightNow",
    default: "AightNow",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className={`font-pretendard w-full h-full flex justify-center items-center`}>
        {children}
      </div>
    </>
  );
}
