import Header from "@/components/Header";

export const metadata = {
  title: {
    template: "%s | AightNow",
    default: "AightNow",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`font-pretendard w-[100vw] h-[100vh] flex flex-col relative`}>
      <Header />
      <section className="bg-background w-full h-full flex justify-start items-start flex-col pt-[150px]  px-[140px] ">
        {children}
      </section>
    </div>
  );
}
