import Header from "@/components/Header";
import SessionProvider from "@/app/(Login)/components/SessionProvider";
import { authConfig } from "@/lib/auth";
import { getServerSession } from "next-auth";
//import AutoLogout from "@/components/AutoLogout/AutoLogout";

export const metadata = {
  title: {
    template: "%s | AightNow",
    default: "AightNow",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authConfig);
  return (
    <SessionProvider session={session}>
      <div className={`font-pretendard w-[100vw] h-[100vh] flex flex-col  relative`}>
        <Header />
        <section className="bg-background w-full h-full flex justify-center items-center flex-col  ">
          <div className=" absolute top-[15%] rounded-3xl w-[590px] min-h-[544px]  px-[102px] py-[50px] bg-white flex flex-col justify-start items-center pb-[20px] ">
            {children}
          </div>
        </section>
      </div>
    </SessionProvider>
  );
}
