import Header from "@/components/Header";

export const metadata = {
  title: {
    template: "MyPage | AightNow",
    default: "AightNow",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`font-pretendard w-[100vw] h-[100vh] flex flex-col relative`}>
      <Header />
      <section className="bg-background w-full h-full flex justify-start items-start flex-col pt-[150px]  px-[140px] ">
        <article className=" w-full h-auto">
          <h1 className=" w-full h-auto text-h4 font-bold text-mainNavy-900 mb-5">마이페이지</h1>
          <div className=" w-full h-auto flex gap-2">{children}</div>
        </article>
      </section>
    </div>
  );
}
